{% set version = "2020-09-16-unicode13_1" %}

package:
  name: font-ttf-noto-emoji
  version: {{ version }}

source:
  url: https://github.com/googlefonts/noto-emoji/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 13ad521b42e395751c72c0bf5585bd354d2383c65abe1a6227743fa8661e0feb

build:
  number: 0
  noarch: generic

test:
  requires:
    # dummy to have at least one test env requirement
    - bzip2
  commands:
    - test -f ${PREFIX}/fonts/NotoEmoji-Regular.ttf       # [unix]

about:
  home: https://www.google.com/get/noto
  dev_url: https://github.com/googlefonts/noto-emoji
  summary: Noto Emoji fonts
  license: OFL-1.1
  license_file: LICENSE
  license_family: OTHER

extra:
  recipe-maintainers:
    - izahn
